[cups] No ulimit for HA OS 16+

diff --git a/cups/rootfs/etc/s6-overlay/s6-rc.d/avahi-daemon/run b/cups/rootfs/etc/s6-overlay/s6-rc.d/avahi-daemon/run
--- a/cups/rootfs/etc/s6-overlay/s6-rc.d/avahi-daemon/run
+++ b/cups/rootfs/etc/s6-overlay/s6-rc.d/avahi-daemon/run
@@ -1,6 +1,34 @@
 #!/usr/bin/with-contenv bashio
 
-ulimit -n 1048576
+# Get OS version from Supervisor API
+bashio::log.info "Fetching OS info from Supervisor API..."
+OS_INFO=$(curl -sf --connect-timeout 5 --max-time 10 -H "Authorization: Bearer ${SUPERVISOR_TOKEN}" \
+    -H "Content-Type: application/json" \
+    http://supervisor/os/info)
+
+if [ -z "$OS_INFO" ]; then
+  bashio::log.error "ERROR: Failed to fetch OS info from Supervisor API."
+  exit 1
+fi
+
+OS_VERSION=$(echo "$OS_INFO" | jq -r '.data.version')
+
+if [ -z "$OS_VERSION" ]; then
+  bashio::log.error "ERROR: Failed to extract OS version from API response."
+  exit 1
+fi
+bashio::log.info "OS Version: $OS_VERSION"
+
+# Check if OS_VERSION is greater than 16
+if (( $(echo "$OS_VERSION >= 16" | bc -l) )); then
+    # Exclude the two variables
+    bashio::log.info "OS version >= 16, not setting ulimit. Current limits:"
+    ulimit -n
+else
+    # Export all variables
+    bashio::log.info "OS version < 16, setting ulimit"
+    ulimit -n 524288
+fi
 
 bashio::log.info "Starting Avahi daemon from S6"
 
